name: upload_download_test

on:
  workflow_dispatch

jobs:
  example-job:
    name: Save output
    runs-on: ubuntu-latest
    steps:
      - name: Install vcpkg packages
        run: c:\vcpkg\vcpkg.exe --triplet=x86-windows-static install libyuv
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: libyuv
          path: c:\vcpkg\downloads
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-log-file
